import type { Metadata } from 'next'
import './globals.css'
import Providers from './providers'
import PageTransition from './PageTransition'
import Navbar from '@/components/AppBar'

export const metadata: Metadata = {
    title: 'Irin Sultana Munni',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <Navbar />
                    <PageTransition>{children}</PageTransition>
                </Providers>
            </body>
        </html>
    )
}
